# Generated by Django 2.1.5 on 2019-01-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20190120_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
