# Generated by Django 2.1.5 on 2019-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20190723_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
