# Generated by Django 2.1.5 on 2019-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_category_place_on_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='place_on_page',
            field=models.IntegerField(choices=[(0, '0'), (1, 'First'), (2, 'Second'), (3, 'Third')], default=0),
        ),
    ]
