# Generated by Django 2.2.4 on 2019-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_auto_20190730_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail image'),
        ),
    ]
