# Generated by Django 2.1.5 on 2019-08-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_productimg_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='view',
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.Product'),
        ),
    ]
